preset: laravel

disabled:
  - concat_without_spaces
  - simplified_null_return
  - no_extra_consecutive_blank_lines
finder:
  not-name:
    - "index.php"
    - "server.php"
    - "AuthServiceProvider.php"
