name: GithubCI

on: [push]

jobs:
  laravel:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [7.2, 7.3, 7.4]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v1
    - uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Show IP
      run: ip a

    - name: Show Python version
      run: python -V

    - name: SQLite Install
      run: sudo apt-get update && sudo apt-get install -y sqlite3

    - name: Install snmp* packets
      run: sudo apt-get install snmp

    - name: Check PHP version
      run: php -v

    - name: Install php-intl
      run: sudo apt-get install php${{ matrix.php-versions }}-intl

    - name: Install php-snmp
      run: sudo apt-get install php${{ matrix.php-versions }}-snmp

    - name: Run SNMP server (Mikrotik cloud)
      run: python /home/runner/work/moring/moring/utils/snmp-server/snmp-server.py -p 9001 -c /home/runner/work/moring/moring/utils/snmp-server/configs/CloudMikrotik.py &

    - name: Run Cisco SNMP server (Cisco)
      run: python /home/runner/work/moring/moring/utils/snmp-server/snmp-server.py -p 9002 -c /home/runner/work/moring/moring/utils/snmp-server/configs/Cisco.py &

    - name: Run SNMP server (DLink)
      run: python /home/runner/work/moring/moring/utils/snmp-server/snmp-server.py -p 9003 -c /home/runner/work/moring/moring/utils/snmp-server/configs/Dlink.py &

    - name: Run SNMP server (Eltex)
      run: python /home/runner/work/moring/moring/utils/snmp-server/snmp-server.py -p 9004 -c /home/runner/work/moring/moring/utils/snmp-server/configs/Eltex.py &

    - name: Run SNMP server (Mikrotik hardware)
      run: python /home/runner/work/moring/moring/utils/snmp-server/snmp-server.py -p 9005 -c /home/runner/work/moring/moring/utils/snmp-server/configs/HardwareMikrotik.py &

    - name: Check SNMP server 1
      run: snmpwalk -v2c -c public 127.0.0.1:9001 SNMPv2-MIB::sysDescr.0

    - name: Check SNMP server 5
      run: snmpwalk -v2c -c public 127.0.0.1:9005 SNMPv2-MIB::sysDescr.0

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing.example', '.env');"

    - name: Enabling parallel installing packages
      run: composer global require hirak/prestissimo

    - name: Install Dependencies
      run: composer install

    - name: Clear artisan config cache
      run: php artisan config:clear

    - name: Generate key
      run: php artisan key:generate

    - name: Create Database folder
      run: mkdir -p database

    - name: Create Database
      run: touch database/database.sqlite

    - name: Apply migrations
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
